### ISSUE TITLE
some question about build

### ISSUE THREAD

**Issue by legend-issue** [angr/tracer#53]
When I try to build tracer,I met some problems.As below:

Traceback (most recent call last):
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/misc/autoimport.py", line 39, in auto_import_modules
    proc_module = importlib.import_module(".%s" % proc_module_name, base_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dynamic_loading
WARNING | 2017-11-22 22:27:28,986 | angr.misc.autoimport | Unable to autoimport module angr.procedures.libc.tolower
Traceback (most recent call last):
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/misc/autoimport.py", line 39, in auto_import_modules
    proc_module = importlib.import_module(".%s" % proc_module_name, base_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tolower
WARNING | 2017-11-22 22:27:28,986 | angr.misc.autoimport | Unable to autoimport module angr.procedures.libc.toupper
Traceback (most recent call last):
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/misc/autoimport.py", line 39, in auto_import_modules
    proc_module = importlib.import_module(".%s" % proc_module_name, base_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named toupper
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tracer
  File "/home/callgraph/tracer/tracer/__init__.py", line 5, in <module>
    from .tracer import *
  File "/home/callgraph/tracer/tracer/tracer.py", line 2, in <module>
    from .exploration_techniques import CrashMonitor, Oppologist
  File "/home/callgraph/tracer/tracer/exploration_techniques/__init__.py", line 111, in <module>
    from .crash_monitor import CrashMonitor
  File "/home/callgraph/tracer/tracer/exploration_techniques/crash_monitor.py", line 6, in <module>
    from .angr import SIM_LIBRARIES, BP_AFTER, BP_BEFORE
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/__init__.py", line 26, in <module>
    from .project import *
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/project.py", line 592, in <module>
    from .analyses.analysis import Analyses
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/analyses/__init__.py", line 15, in <module>
    from .veritesting import Veritesting
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/analyses/veritesting.py", line 20, in <module>
    class CallTracingFilter(object):
  File "/home/callgraph/tracer/tracer/exploration_techniques/angr/analyses/veritesting.py", line 26, in CallTracingFilter
    SIM_PROCEDURES['cgc']['receive'],
KeyError: 'receive'

I try many ways but do not work.

**Comment by zardus** [comment]
Please start with the docker container (`docker run -it shellphish/mechaphish`). It’ll have everything installed. To see how it does it, check out the relevant dockerfiles in both github.com/angr/angr-dev and github.com/mechaphish/setup.
